# SonarQube Project Configuration
sonar.organization=costa
sonar.projectKey=node-jws
sonar.projectName=node-jws
# sonar.projectVersion is set dynamically by the reusable workflow (-Dsonar.projectVersion=${BRANCH_NAME})

# Source Code Configuration
sonar.sources=index.js,lib
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**/*,coverage/**/*,Makefile,test/**/*
